import json, os

GT_PATH = os.path.join('data', 'evaluation_sets', 'test_cases_ground_truth_extended.json')
OUT_DIR = os.path.join('data', 'evaluation_sets')
TXT_OUT = os.path.join(OUT_DIR, 'dataset_stats.txt')
IMG_OUT = os.path.join(OUT_DIR, 'intent_distribution.png')

os.makedirs(OUT_DIR, exist_ok=True)

with open(GT_PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)

# support both formats: {"cases": [...]} or [...] 
if isinstance(data, dict) and 'cases' in data:
    cases = data['cases']
elif isinstance(data, list):
    cases = data
else:
    # try common key names
    cases = data.get('cases', []) if isinstance(data, dict) else []

count_intent = {}
count_diff = {}
count_merchant = {}
for c in cases:
    intent = c.get('intent_label') or c.get('intent') or 'UNKNOWN'
    diff = c.get('difficulty') or 'UNKNOWN'
    merchant = c.get('merchant') or 'UNKNOWN'
    count_intent[intent] = count_intent.get(intent, 0) + 1
    count_diff[diff] = count_diff.get(diff, 0) + 1
    count_merchant[merchant] = count_merchant.get(merchant, 0) + 1

with open(TXT_OUT, 'w', encoding='utf-8') as f:
    f.write('Dataset statistics generated by scripts/generate_report_assets.py\n')
    f.write('\nTotal cases: {}\n'.format(len(cases)))
    f.write('\nIntent distribution:\n')
    for k, v in sorted(count_intent.items(), key=lambda x: -x[1]):
        f.write(f'  {k}: {v}\n')
    f.write('\nDifficulty distribution:\n')
    for k, v in sorted(count_diff.items(), key=lambda x: -x[1]):
        f.write(f'  {k}: {v}\n')
    f.write('\nMerchant distribution:\n')
    for k, v in sorted(count_merchant.items(), key=lambda x: -x[1]):
        f.write(f'  {k}: {v}\n')

print('WROTE', TXT_OUT)

# try to create a plot if matplotlib available
try:
    import matplotlib.pyplot as plt
    labels = list(count_intent.keys())
    vals = [count_intent[l] for l in labels]
    plt.figure(figsize=(6,3))
    plt.bar(labels, vals, color='C0')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.savefig(IMG_OUT, dpi=150)
    plt.close()
    print('SAVED_PLOT', IMG_OUT)
except Exception as e:
    print('NO_PLOT', str(e))
